[package]
name = "foxbook-setup"
version = "0.2.0"
authors = ["Ryan1729 <ryan1729@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
